INSERT INTO t_arme (arme_id, type, nom, description, prix, `force`, max_utilisation) VALUES
(1, 'Fusil d\'assaut', 'FAMAS', 'Le FAMAS est un fusil d\'assaut bullpup français, utilisé par l\'armée française. Il est connu pour sa cadence de tir élevée.', 2500, 25, 8000),
(2, 'Fusil d\'assaut', 'AK-47', 'L\'AK-47 est un fusil d\'assaut soviétique, réputé pour sa robustesse et sa simplicité d\'utilisation.', 2300, 30, 10500),
(3, 'Fusil d\'assaut', 'M16', 'Fusil d\'assaut américain, léger et précis, utilisé par les forces armées américaines.', 2200, 28, 10700),
(4, 'Fusil d\'assaut', 'M4A1', 'Version moderne et améliorée du M16, plus compact et adapté aux opérations spéciales.', 2400, 30, 9700),
(5, 'Fusil de précision', 'Barrett M82', 'Le Barrett M82 est un fusil de précision semi-automatique de gros calibre, capable de tirer sur des cibles à très longue distance.', 3500, 100, 6200),
(6, 'Fusil de précision', 'Dragunov', 'Le Dragunov est un fusil de sniper soviétique utilisé dans de nombreuses forces armées du monde.', 2800, 85, 9000),
(7, 'Pistolet', 'Glock 17', 'Le Glock 17 est un pistolet semi-automatique autrichien, reconnu pour sa fiabilité et sa simplicité d\'utilisation.', 600, 10, 8700),
(8, 'Pistolet', 'Beretta 92', 'Le Beretta 92 est un pistolet semi-automatique italien, très utilisé par les forces de l\'ordre et l\'armée.', 650, 12, 9800),
(9, 'Pistolet', 'Desert Eagle', 'Le Desert Eagle est un pistolet semi-automatique de gros calibre, souvent utilisé pour les tirs à grande distance.', 1200, 25, 3500),
(10, 'Pistolet', 'SIG Sauer P226', 'Le SIG Sauer P226 est un pistolet très précis, utilisé par de nombreuses unités spéciales et forces de police.', 700, 15, 6500),
(11, 'Mitraillette', 'MP5', 'Le MP5 est une mitraillette compacte et fiable, très populaire dans les forces spéciales et la police.', 2000, 25, 8000),
(12, 'Mitraillette', 'Uzi', 'L\'Uzi est une mitraillette compacte, très populaire dans les années 1980 et encore utilisée par certains corps militaires et policiers.', 1500, 20, 8500),
(13, 'Mitraillette', 'Thompson', 'La Thompson, surnommée la "Tommy Gun", est une mitraillette emblématique de la Seconde Guerre mondiale.', 1700, 22, 7200),
(14, 'Fusil à pompe', 'Remington 870', 'Le Remington 870 est un fusil à pompe très utilisé par les forces de police et dans le cadre de la chasse.', 800, 35, 5500),
(15, 'Fusil à pompe', 'Benelli M4', 'Le Benelli M4 est un fusil à pompe semi-automatique, réputé pour sa fiabilité et sa rapidité de tir.', 1200, 40, 6000),
(16, 'Fusil à pompe', 'Mossberg 500', 'Le Mossberg 500 est un fusil à pompe polyvalent, utilisé dans des contextes militaires et civils.', 900, 38, 5300),
(17, 'Mitrailleuse', 'M240', 'La M240 est une mitrailleuse lourde utilisée par l\'armée américaine, capable de tirer en rafale à grande cadence.', 4500, 50, 7000),
(18, 'Mitrailleuse', 'M60', 'La M60 est une mitrailleuse de soutien, utilisée principalement pendant les années 1960 et 1970 dans de nombreuses armées.', 5000, 55, 3300),
(19, 'Mitrailleuse', 'PKM', 'Le PKM est une mitrailleuse soviétique qui a été largement utilisée dans les armées du Pacte de Varsovie et les conflits modernes.', 4800, 60, 5400),
(20, 'Fusil de chasse', 'Winchester Model 70', 'Le Winchester Model 70 est un fusil de chasse précis et populaire dans les compétitions de tir sportif.', 1300, 35, 7000),
(21, 'Fusil de chasse', 'Remington 700', 'Le Remington 700 est un fusil de chasse, également utilisé pour le tir sportif et la chasse de gros gibier.', 1400, 40, 9500),
(22, 'Fusil de chasse', 'Browning A-Bolt', 'Le Browning A-Bolt est un fusil de chasse robuste, conçu pour le tir de gros gibier.', 1600, 42, 9700),
(23, 'Arbalète', 'Barnett Jackal', 'L\'arbalète Barnett Jackal est une arbalète à haute vitesse, idéale pour la chasse et les compétitions.', 500, 15, 12250),
(24, 'Arbalète', 'Excalibur Matrix', 'L\'Excalibur Matrix est une arbalète puissante, très utilisée pour la chasse au gros gibier.', 700, 20, 11950),
(25, 'Arbalète', 'Parker Hale', 'L\'arbalète Parker Hale est une arme de précision, très prisée pour la chasse sportive.', 600, 18, 10750),
(26, 'Lance-roquettes', 'RPG-7', 'Le RPG-7 est un lance-roquettes portable, utilisé par de nombreuses armées et groupes insurgés dans le monde.', 3500, 150, 10900),
(27, 'Lance-roquettes', 'AT4', 'L\'AT4 est un lance-roquettes antichar utilisé par les forces militaires, idéal pour détruire des véhicules blindés.', 4000, 180, 10095),
(28, 'Lance-roquettes', 'M72 LAW', 'Le M72 LAW est un lance-roquettes léger à usage unique, utilisé par les armées pour détruire des cibles blindées.', 2500, 100, 13235),
(29, 'Grenade', 'M67', 'La grenade M67 est une grenade à fragmentation utilisée par les armées américaines.', 200, 30, 11320),
(30, 'Grenade', 'RGD-5', 'La grenade RGD-5 est une grenade à fragmentation de conception soviétique, couramment utilisée dans les anciennes républiques soviétiques.', 150, 28, 11140),
(31, 'Grenade', 'F1', 'La grenade F1 est une grenade à fragmentation utilisée par l\'armée française.', 180, 32, 12225),
(32, 'Lance-flammes', 'M2 Flamethrower', 'Le M2 Flamethrower est un lance-flammes utilisé par l\'armée américaine pendant la Seconde Guerre mondiale.', 3000, 75, 13000),
(33, 'Lance-flammes', 'FLA-100', 'Le FLA-100 est un lance-flammes portable utilisé pour détruire les positions ennemies et les véhicules.', 3500, 85, 15000),
(34, 'Lance-flammes', 'L1A1', 'Le L1A1 est un lance-flammes britannique, utilisé par les forces armées britanniques et du Commonwealth.', 4000, 90, 8900),
(35, 'Couteau', 'Ka-Bar', 'Le Ka-Bar est un couteau de combat américain, utilisé depuis la Seconde Guerre mondiale.', 150, 10, 20000),
(36, 'Couteau', 'Gerber StrongArm', 'Le Gerber StrongArm est un couteau de survie, conçu pour une utilisation dans des conditions extrêmes.', 120, 8, 15000),
(37, 'Couteau', 'SOG Seal Pup', 'Le SOG Seal Pup est un couteau de combat léger et polyvalent, souvent utilisé par les Navy SEALs.', 130, 9, 17000),
(38, 'Dague', 'Fairbairn-Sykes', 'La dague Fairbairn-Sykes est une arme blanche de combat utilisée par les troupes spéciales britanniques pendant la Seconde Guerre mondiale.', 100, 12, 8972),
(39, 'Dague', 'Bowie', 'Le couteau Bowie est une dague à large lame, utilisée par les pionniers américains au 19ème siècle.', 90, 10, 10000),
(40, 'Dague', 'Push Dagger', 'La Push Dagger est une dague de combat compacte, idéale pour les situations de self-défense.', 75, 8, 14000),
(41, 'Arc', 'Hoyt Carbon RX-7', 'L\'Hoyt Carbon RX-7 est un arc de chasse haut de gamme, connu pour sa précision et sa légèreté.', 1200, 40, 13000),
(42, 'Arc', 'Bowtech Revolt', 'Le Bowtech Revolt est un arc de chasse moderne, avec une grande puissance de tir.', 1300, 42, 13500),
(43, 'Arc', 'Mathews VXR', 'Le Mathews VXR est un arc à poulies, utilisé par les archers de compétition et pour la chasse.', 1400, 45, 14050),
(44, 'Fusil de précision', 'CheyTac M200', 'Le CheyTac M200 est un fusil de sniper de très haute précision, utilisé pour des tirs à longue distance.', 9000, 120, 15050),
(45, 'Fusil de précision', 'AI Arctic Warfare', 'L\'Arctic Warfare est un fusil de précision de haute qualité, souvent utilisé dans des environnements froids et extrêmes.', 8500, 110, 18060),
(46, 'Mitrailleuse', 'FN MAG', 'La FN MAG est une mitrailleuse belge de calibre 7,62 mm, utilisée par de nombreuses armées à travers le monde.', 4000, 60, 13000),
(47, 'Mitrailleuse', 'Minimi', 'Le Minimi est une mitrailleuse légère à munitions de calibre 5,56 mm, utilisée par de nombreuses forces armées, notamment les États-Unis.', 3700, 55, 13900),
(48, 'Pistolet-mitrailleur', 'PP-19 Bizon', 'Le PP-19 Bizon est un pistolet-mitrailleur russe, connu pour son chargeur tambour de grande capacité.', 1800, 25, 15500),
(49, 'Lance-grenades', 'M203', 'Le M203 est un lance-grenades à main monté sous un fusil d\'assaut, très utilisé par les forces militaires américaines.', 1500, 40, 14000),
(50, 'Fusil de précision', 'AWP', 'L AWP est un fusil de précision à verrou utilisé principalement par les tireurs d élite pour sa grande portée et sa puissance de feu.', 2700, 10, 15000);